# Generated by Django 3.0.1 on 2020-01-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ploki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='maili',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
